services:
  lastfm-app:
    build: .
    container_name: lastfm-app
    restart: unless-stopped
    ports:
      - "9090:80"
    env_file:
      - .env
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
